### ISSUE TITLE
数据库连接问题

### ISSUE THREAD

**Issue by maskwang520** [zhongmc1995/blog#2]
今天看了楼主的项目，为啥，里面有些文件找不到。然后连接数据库有问题

**Comment by zhongmc1995** [comment]
你是指什么文件少了，同时数据什么问题

**Comment by zhongmc1995** [comment]
你是指少了那些文件发自我的iPhone------------------ 原始邮件 ------------------发件人: 汪志峰  <notifications@github.com>发送时间: 2017年8月10日 13:34收件人: zhongmc1995/blog <blog@noreply.github.com>抄送: Subscribed <subscribed@noreply.github.com>主题: 回复：[zhongmc1995/blog] 数据库连接问题 (#2)今天看了楼主的项目，为啥，里面有些文件找不到。然后连接数据库有问题

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/zhongmc1995/blog","title":"zhongmc1995/blog","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/zhongmc1995/blog"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"数据库连接问题 (#2)"}],"action":{"name":"View Issue","url":"https://github.com/zhongmc1995/blog/issues/2"}}}

**Comment by maskwang520** [comment]
可以微信或者qq联系你吗？谢谢你。我微信 maskwang12345

**Comment by maskwang520** [comment]
![bg1 m 4 qf 2ey h zeg](https://user-images.githubusercontent.com/13582238/29156388-3ca1e470-7dd4-11e7-8da0-c7b20ad5e30b.png)

**Comment by zhongmc1995** [comment]
晚上加你。我上班发自我的iPhone------------------ 原始邮件 ------------------发件人: 汪志峰  <notifications@github.com>发送时间: 2017年8月10日 13:56收件人: zhongmc1995/blog <blog@noreply.github.com>抄送: 钟明城 <zhongmc_me@163.com>, Comment <comment@noreply.github.com>主题: 回复：[zhongmc1995/blog] 数据库连接问题 (#2)可以微信或者qq联系你吗？谢谢你。我微信 maskwang12345

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/zhongmc1995/blog","title":"zhongmc1995/blog","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/zhongmc1995/blog"}},"updates":{"snippets":[{"icon":"PERSON","message":"@maskwang520 in #2: 可以微信或者qq联系你吗？谢谢你。我微信 maskwang12345"}],"action":{"name":"View Issue","url":"https://github.com/zhongmc1995/blog/issues/2#issuecomment-321458228"}}}
